liip_imagine:
    resolvers:
       profile_photos:
          web_path:
            # use %kernel.project_dir%/web for Symfony prior to 4.0.0
            web_root: "%kernel.project_dir%/public"
            cache_prefix: "media/cache"


    driver:               gd

    controller:
        filter_action:          liip_imagine.controller:filterAction
        filter_runtime_action:  liip_imagine.controller:filterRuntimeAction
        redirect_response_code: 302
    webp:
        generate:    false
        quality:     100
        cache:       photo
        data_loader: ~
        post_processors: []
        
    filter_sets:
        my_thumb_jpeg:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [360, 300], mode: inset }
        my_thumb_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [360, 300], mode: inset }