liip_imagine:
    driver: "gd"
    
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public"


    resolvers:
        thumbnails:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "uploads/thumbnails"

    filter_sets:

        my_thumb:
            quality: 100
            jpeg_quality: 100
            png_compression_level: 0
            cache: thumbnails

            filters:

                thumbnail: { size: [360, 240], mode: outbound }